version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: videngine_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - infrastructures_default
    ports:
      - "6999:5432"

volumes:
  pgdata:

networks:
  infrastructures_default:
    external: true # Must exist already

